### ISSUE TITLE
[Request] Implementation of Repacker/Injector?

### ISSUE THREAD

**Issue by Medstar117** [Nibre/HaloWwise#1]
Hello there; I just wanted to say thank you SO much for this project, as they have been helping me to figure out how to add custom sounds/music to Halo Wars: Definitive Edition! Your dumping script has to be the best around, as it's making it a lot easier for me to trace names to sound banks and files.

If you don't mind, and since you said it wouldn't be hard to implement, do you think you could make the re-packer/injector possible for this project? That would save me a lot of time in trying to figure it out myself. And if not, then it's no big deal; I figured I'd ask just to see.

**Comment by JaneDough2022** [comment]
Hey, I need a bit of help with compiling this as I'm very new to the programming business. If you can, message me on how to do it, or you can send me your copy of the exe. I'm a big noob at doing this in Microsoft Visual Studio.

**Comment by Medstar117** [comment]
I have decided to take this task upon myself and am having quite a bit of fun with it XD

I'll be closing this issue with that statement. If one's interested, the project will eventually be on my GitHub.

**Comment by JaneDough2022** [comment]
> I have decided to take this task upon myself and am having quite a bit of fun with it XD
> 
> I'll be closing this issue with that statement. If one's interested, the project will eventually be on my GitHub.

I'll keep a lookout for it on your GitHub page.
